[platformio]
default_envs = xiao_esp32c3

[env:xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_src_filter =
	+<main_xiao.cpp>
	-<blink_test.cpp>
	-<main.cpp>
	-<main_xiao_webui.cpp>
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit ADXL345@^1.3.4

[env:xiao_blink_test]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_src_filter =
	+<blink_test.cpp>
	-<main_xiao.cpp>
	-<main.cpp>
	-<main_xiao_webui.cpp>

[env:xiao_webui]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200
build_src_filter =
	+<main_xiao_webui.cpp>
	-<blink_test.cpp>
	-<main_xiao.cpp>
	-<main.cpp>
lib_deps = 
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit ADXL345@^1.3.4
	me-no-dev/ESPAsyncWebServer@^1.2.3
	me-no-dev/AsyncTCP@^1.1.1
	bblanchon/ArduinoJson@^7.0
build_flags =
	-DBOARD_HAS_PSRAM
